### ISSUE TITLE
Wrong separator character for CLN channel ids

### ISSUE THREAD

**Issue by kristapsk** [synonymdev/lightning-channel-id-js#4]
It uses `x` not `:` for a long time.

See https://bitcoin.stackexchange.com/questions/78029/how-to-convert-channel-id-from-c-lightning-to-lnd/79427#comment98170_78029:
> In the spec meeting in November it was agreed to make the format of the short channel Id part of the protocol. In future implementations should use the clightning format with `x` as a separator instead of `:` while colon was very readable the short channel ids that use x as a separator are doubleclickable.

**Comment by kristapsk** [comment]
Looked more carefully, I see you support any separator, but default should be `x` not `:`.

**Comment by rbndg** [comment]
yeah my plan is to, change the interface, so there is just 1 function and it will parse the argument and decide what to do with it

**Comment by rbndg** [comment]
Fixed with latest version
